### ISSUE TITLE
Permision denied

### ISSUE THREAD

**Issue by ghost** [spff/install-supersu-via-adb#1]
I did as requested but it doesn't work, it says persmision denied

**Comment by spff** [comment]
During step 6?

**Comment by ghost** [comment]
> During step 6?

Yes

**Comment by spff** [comment]
Please try directly run the commands in the shell script line by line.  
I guess you'll failed on the first command `adb root` which means your OS is built as production rather than dev so the adb isn't able to get root permission.  
This repo assumes you can run adb as root so you can manually install SuperSu.  
If you want to root your device (usually mobile phones), please head to xda forum.

**Comment by ghost** [comment]
> Please try directly run the commands in the shell script line by line.  
> I guess you'll failed on the first command `adb root` which means your OS is built as production rather than dev so the adb isn't able to get root permission.  
> This repo assumes you can run adb as root so you can manually install SuperSu.  
> If you want to root your device (usually mobile phones), please head to xda forum.  

ight man, thanks

**Comment by ghost** [comment]
well no, the rist commands went just fine, the problem was during the last
step. it said permision denied. Now im sure it was my fault so, thanks

lun., 20 dec. 2021, 10:10 Chin-Wei Chang ***@***.***> a scris:
